GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTY0NTM5NzQzMSwiZXhwIjoxNjQ1Mzk3NDQ2fQ.45GISk9TNL758LeT84nvYvJknS1s0JFeewdogr13bTI
###

POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTY0NTM5NzY4M30.KaV7fstF5NURNrWA5Rigszj3WLLytAkIfANa_k9s0L0"
}

###

DELETE http://localhost:5000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTY0NTM5NzY4M30.KaV7fstF5NURNrWA5Rigszj3WLLytAkIfANa_k9s0L0"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "Paul"
}


###

POST http://localhost:5000/user/register
Content-Type: application/json

{
    "first_name": "Paul",
    "last_name": "Pirie",
    "email": "pauljohnpirie@yahoo.co.uk",
    "password": "123",
    "phone": "07575939905"
}

###

POST http://localhost:5000/user/appointment/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzZhZTY4MDdjMTU4ODFjZWEwNzJjMyIsImlhdCI6MTY0ODE0MDIzMSwiZXhwIjoxNjQ4MTQwNTMxfQ.GDeqRe6VZLCVzk2PUc-zLA2WduKptdOccOMJ8D34_Nk eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzZhZTY4MDdjMTU4ODFjZWEwNzJjMyIsImlhdCI6MTY0ODAyNDAyN30.mJfcyW1JZN8OAuK20kMz3SnsjBQtuE1b1AtujnWP8HY

{
    "type": "BLOOD_TEST", 
    "number": "001",
    "location": "Stobhill Hospital",
    "ward": "4A",
    "date": "13/01/22",
    "time": "13:30"
}

###

POST http://localhost:5000/hospital/new
Content-Type: application/json

{
    "name": "Glasgow Royal Infirmary",
    "address": "84 Castle St, Glasgow",
    "postcode": "G4 0SF",
    "number": "0141 211 4000",
    "website": "https://www.nhsggc.org.uk/patients-and-visitors/main-hospital-sites/glasgow-royal-campus/glasgow-royal-infirmary/",
    "parking": true,
    "transport": "On-Site",
    "description": "The Glasgow Royal Infirmary is a large teaching hospital. With a capacity of around 1,000 beds, the hospital campus covers an area of around 8 hectares, situated on the north-eastern edge of the city centre of Glasgow, Scotland. It is managed by NHS Greater Glasgow and Clyde.",
    "mapHTML": "<iframe src='https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d35815.04456701567!2d-4.261330281315463!3d55.87237689116133!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x488844025d1da12f%3A0x973cf4cc9403e9f7!2sglasgow%20hospitals!3m2!1d55.8646816!2d-4.2336462!5e0!3m2!1sen!2suk!4v1647859795970!5m2!1sen!2suk'></iframe>"
}

###

POST http://localhost:5000/appointment/type/new
Content-Type: application/json

{
    "title": "Ultrasound Scan",
    "description": "An ultrasound scan can be used to monitor an unborn baby, diagnose a condition, or guide a surgeon during certain procedures.",
    "identifier": "ULTRASOUND_SCAN"
}